### PR TITLE
preview at eassy-hugo-url

### PR DESCRIPTION
**Pull request by cescoferraro**
preview at eassy-hugo-url

### CODE REVIEW

**Comment by masasam** [comment]
Hi @cescoferraro 
Thanks for Pull Request.
This can not merge because the preview does not work.

**Comment by cescoferraro** [comment]
This works for me. @masasam what error are you getting?

```
(defun cesco/easy-hugo-preview ()
  "Preview hugo at localhost."
  (interactive)
  (easy-hugo-with-env
   (if (process-live-p easy-hugo--server-process)
       (browse-url easy-hugo-url)
     (progn
       (setq easy-hugo--server-process
	     (start-process "hugo-server" easy-hugo--preview-buffer "hugo" "server"))
       (browse-url easy-hugo-url)
       (run-at-time easy-hugo-previewtime nil 'easy-hugo--preview-end)))))

(defun cesco/easy-hugo ()
  (interactive)
  (evil-define-key
    (list 'normal 'insert 'visual 'motion)
    easy-hugo-mode-map
    "n" 'easy-hugo-newpost
    "p" 'cesco/easy-hugo-preview
    (kbd "RET") 'easy-hugo-preview)
  (define-key global-map (kbd "C-c C-e") 'easy/hugo)  )


(use-package easy-hugo
  :after (helm-ag)
  :ensure t
  :config
  (setq easy-hugo-basedir "~/go/src/github.com/cescoferraro/me/"
	easy-hugo-postdir "content/blog"
        easy-hugo-url "http://127.0.0.1:1313/me"
        easy-hugo-sshdomain "me"
        easy-hugo-root "~/go/src/github.com/cescoferraro/me/"
        easy-hugo-previewtime "30000")
  (add-hook 'easy-hugo-mode-hook 'cesco/easy-hugo))


```

**Comment by masasam** [comment]
Because preview of existing user does not work with as it is, I will merge if your Pull Request which like following

(defcustom easy-hugo-preview-url "http://localhost:1313/"
  "Preview url of easy-hugo."
  :group 'easy-hugo
  :type 'string)

Please fix your Pull Request with easy-hugo-preview-url.

**Comment by masasam** [comment]
Hi @cescoferraro 

Because preview of existing user does not work with as it is, I will merge if your Pull Request which like following

(defcustom easy-hugo-preview-url "http://localhost:1313/"
"Preview url of easy-hugo."
:group 'easy-hugo
:type 'string)

Please fix your Pull Request with easy-hugo-preview-url.

**Comment by cescoferraro** [comment]
Forgot the default value. Will push the fix in a sec.

**Comment by masasam** [comment]
Hi @cescoferraro 

Since easy-hugo-url is used in another place, Please create a new easy-hugo-preview-url.

(defcustom easy-hugo-preview-url "http://localhost:1313/"
"Preview url of easy-hugo."
:group 'easy-hugo
:type 'string)

**Pull request merged**
