### PR TITLE
easy-hugo-postdir variable

### PR DESCRIPTION
**Pull request by cescoferraro**
The mode is awesome! thanks for the library  👍  🥇 

Themes like https://github.com/nishanths/cocoa-hugo-theme store its posts under `content/blog` instead of `content/post`. I not sure if this is the best approach to deal with the slashes thing, I am a lisp newbie. Please help @masasam

### CODE REVIEW

**Comment by masasam** [comment]
Hi @cescoferraro .
Thank you for Pull Request.
I will want to merge your Pull Request.
Please correct the following defcustom and send it again.

(defcustom easy-hugo-postdir "content/post"
  "Directory where the theme store it's posts."
  :group 'easy-hugo
  :type 'string)

Because if the default is "content/blog", which confuses existing users.

cocoa-hugo-theme user should add the following settings to init.el or .emacs.

(setq easy-hugo-postdir "content/blog")

I will add it to the README.

**Comment by cescoferraro** [comment]
@masasam here you go

**Comment by cescoferraro** [comment]
@masasam does this gets publish to melpa automatically?

**Comment by masasam** [comment]
@cescoferraro yes, It is automatically published to melpa once every 6 hours so wait for a while

**Pull request merged**
